---
name: 'molecule community EEs'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'

jobs:
  molecule-community-ees:
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
    container:
      image: '${{ matrix.container.image }}'
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
      options: '--user root --privileged'
    strategy:
      matrix:
        container:
          # yamllint disable-line rule:line-length
          - image: 'ghcr.io/ansible-community/community-ee-base:2.16.6-1'
    steps:
      - name: 'Install NodeJS'
        uses: 'actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b' # v4.0.3
        with:
          node-version: '20.17.0'
...
