---
name: 'molecule community EEs'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'

jobs:
  molecule-community-ees:
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
    container:
      image: '${{ matrix.container.image }}'
      credentials:
        username: '${{ secrets.crc_username }}'
        password: '${{ secrets.crc_password }}'
      options: '--privileged'
    strategy:
      matrix:
        container:
          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16.8-5@sha256:5728903400b4b797eb697c1db419f2676d4a2aa67404f1e6f6a15d8f6c3d0252'
    steps:
      - name: 'Install NodeJS'
        uses: 'actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b' # v4.0.3
        with:
          node-version: '20.17.0'
...
